spring:
  application:
    name: demo-service-discovery
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  config:
    import: configserver:http://127.0.0.1:4050/demo/config
  cloud:
    config:
      fail-fast: true
      username: config
      password: Secret

server:
  port: 4060
  servlet:
    context-path: /demo/discovery
    application-display-name: ${spring.application.name}
