spring:
  application:
    name: demo-trip-service
  banner:
    charset: UTF-8
    location: classpath:banner.txt

server:
  port: 4042
  servlet:
    context-path: /demo
    application-display-name: ${spring.application.name}
