spring:
  application:
    name: demo-trip-service
  banner:
    charset: UTF-8
    location: classpath:banner.txt

server:
  port: 4042
  servlet:
    #TODO: 0.1 Change contest-path to /demo and put /api/v1 in TripController
    context-path: /demo
    application-display-name: ${spring.application.name}
