spring:
  application:
    name: demo-config-server
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  cloud:
    config:
      server:
        git:
          clone-on-start: true
          timeout: 10
          uri: https://github.com/cjeronimomx/demo-config-properties.git
          search-paths:
            - '{application}'
          username: ${GIT_USER}
          password: ${GIT_PASSWD}
  security:
    user:
      name: config
      password: Secret

server:
  port: 4050
  servlet:
    context-path: /demo/config
    application-display-name: ${spring.application.name}
