spring:
  application:
    name: demo-api-gateway
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  config:
    import: configserver:http://127.0.0.1:4050/demo/config
  cloud:
    config:
      fail-fast: true
      username: config
      password: Secret

server:
  port: 4070
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}

#TODO: 2. Search NoopSpan in API Gateway logs and into driver, passenger, trip services
logging:
  level:
    root: DEBUG
    com.demo.demo.gateway: DEBUG


