#TODO: 0.2 Rename this class with application.yml
#TODO: 0.3 Add banner.txt file

#TODO: 1. Configure properties for this metrics server and config server connection
spring:
  application:
    name: demo-metrics-server
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  config:
    import: configserver:http://127.0.0.1:4050/demo/config
  cloud:
    config:
      fail-fast: true
      username: config
      password: Secret

server:
  port: 4080
  servlet:
    context-path: /
    application-display-name: ${spring.application.name}

