spring:
  application:
    name: demo-passenger-service
  banner:
    charset: UTF-8
    location: classpath:banner.txt

server:
  port: 4041
  servlet:
    context-path: /demo
    application-display-name: ${spring.application.name}
