spring:
  application:
    name: demo-passenger-service
  banner:
    charset: UTF-8
    location: classpath:banner.txt

  config:
    import: configserver:http://127.0.0.1:4050/demo/config
  cloud:
    config:
      fail-fast: true
      username: config
      password: Secret

server:
  #TODO: 5. Test running many microservice instance and validate in the service discovery
  port: 4041
  servlet:
    context-path: /demo
    application-display-name: ${spring.application.name}
